<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-06T05:47:26Z" name="Suite_Automation" finished-at="2021-09-06T05:47:51Z" duration-ms="24869">
    <groups>
      <group name="Login">
        <method signature="VerifyAmazonTest.verifyPasswordErrorTest(java.lang.reflect.Method)[pri:2, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" name="verifyPasswordErrorTest" class="com.qa.amazon.tests.VerifyAmazonTest"/>
      </group> <!-- Login -->
      <group name="Home">
        <method signature="VerifyAmazonTest.verifyHomePageTitleTest(java.lang.reflect.Method)[pri:1, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" name="verifyHomePageTitleTest" class="com.qa.amazon.tests.VerifyAmazonTest"/>
      </group> <!-- Home -->
    </groups>
    <test started-at="2021-09-06T05:47:26Z" name="AutomationTest" finished-at="2021-09-06T05:47:51Z" duration-ms="24869">
      <class name="com.qa.amazon.tests.VerifyAmazonTest">
        <test-method is-config="true" signature="before()[pri:0, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" started-at="2021-09-06T05:47:26Z" name="before" finished-at="2021-09-06T05:47:35Z" duration-ms="8954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method signature="verifyHomePageTitleTest(java.lang.reflect.Method)[pri:1, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" started-at="2021-09-06T05:47:35Z" name="verifyHomePageTitleTest" finished-at="2021-09-06T05:47:36Z" duration-ms="406" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.amazon.tests.VerifyAmazonTest.verifyHomePageTitleTest(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitleTest -->
        <test-method signature="verifyPasswordErrorTest(java.lang.reflect.Method)[pri:2, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" started-at="2021-09-06T05:47:36Z" name="verifyPasswordErrorTest" finished-at="2021-09-06T05:47:44Z" duration-ms="8569" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.amazon.tests.VerifyAmazonTest.verifyPasswordErrorTest(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.amazon.tests.VerifyAmazonTest.verifyPasswordErrorTest(VerifyAmazonTest.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPasswordErrorTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.amazon.tests.VerifyAmazonTest@71a8adcf]" started-at="2021-09-06T05:47:51Z" name="tearDown" finished-at="2021-09-06T05:47:51Z" duration-ms="736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.amazon.tests.VerifyAmazonTest -->
    </test> <!-- AutomationTest -->
  </suite> <!-- Suite_Automation -->
</testng-results>
